#!/bin/bash

if [ -n "${TIMEZONE}" ] && [ -f /usr/share/zoneinfo/${TIMEZONE} ]; then

	echo ${TIMEZONE} > /etc/timezone
	rm /etc/localtime
	ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
	dpkg-reconfigure -f noninteractive tzdata
	
else

	echo "TIMEZONE ${TIMEZONE} not defined or not present."
    exit
    
fi

JAR_FILE=/usr/share/cointrader/cointrader.jar
CONFIG_FILE=/data/conf/${HOSTNAME}.conf
LOG_FILE=/data/log/${HOSTNAME}.log

if [ -f "$CONFIG_FILE" ]; then

	echo "" >> ${LOG_FILE}	
	java -jar ${JAR_FILE} -f ${CONFIG_FILE} >> ${LOG_FILE}
	
else

    echo "The file ${CONFIG_FILE} does not exist."
    exit
    
fi
