version: '3.7'

services:
  cointrader:
    hostname: ${HOSTNAME}
    container_name: ${HOSTNAME}
    image: nucleodevel/cointrader:latest    
    volumes:
     - cointrader:/data
    environment:
      - CONFFILE=${CONFFILE}
      - TIMEZONE=${TIMEZONE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
volumes:
  cointrader:
    external: true
    