version: '3.8'

services:
  app:
    hostname: cointrader
    image: nucleodevel/cointrader:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
      restart_policy:
        condition: on-failure
      rollback_config:
        order: start-first
      update_config:
        failure_action: rollback
        order: start-first 
    volumes:
     - cointrader:/data
    environment:
      - CONFFILE=${CONFFILE}
      - TIMEZONE=${TIMEZONE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rede-proxy

networks:
  rede-proxy:
    name: rede-swarm-cointrader
    
volumes:
  cointrader:
    external: true
    